language: java

jdk:
  - oraclejdk8

script: "mvn clean install -DskipTests=true"

services:
  - redis

# whitelist
branches:
  only:
    - devel

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
