language: java

os:
  - linux

branches:
  only:
  - develop
  
jdk:
  - openjdk8

before_script:
  - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

install:
#  - mvn -T 1C install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml -Dfailsafe.timeout=0

script:
  - travis_wait 30 mvn -T 1C install -f driver/pom.xml -Dfailsafe.timeout=0
  - travis_wait 30 mvn -T 1C install -f server/pom.xml -Dfailsafe.timeout=0
